[package]
name = "sam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minicaldav = "0.8.0"
ureq = "2.7.1"
url = { version = "2" }
thiserror = "1.0.43"
toml = "0.7.6"
chrono = "0.4.26"

